export const courses = [
  {
    id: "machine-learning-with-python",
    title: "Machine Learning with Python",
    instructor: "Krishna Kanth",
    lectures: 25,
    weeks: 7,
    price: 5000,
    image: "/data-science.jpg",
    level: "Intermediate",
    students: "8,240",
    description: "Master Machine Learning concepts and build predictive models using Python. This hands-on internship covers supervised and unsupervised learning, neural networks, and real-world deployment."
  },
  {
    id: "artificial-intelligence",
    title: "Artificial Intelligence",
    instructor: "Kranthi",
    lectures: 25,
    weeks: 9,
    price: 5000,
    image: "/ai-course.jpg",
    level: "Advanced",
    students: "5,120",
    description: "Dive deep into AI. Learn how to build intelligent agents, understand natural language processing, and explore the foundations of modern AI technologies."
  },
  {
    id: "data-science",
    title: "Data Science",
    instructor: "Krishna Kanth",
    lectures: 26,
    weeks: 7,
    price: 5000,
    image: "/data-science.jpg",
    level: "Beginner to Intermediate",
    students: "10,400",
    description: "Learn to extract actionable insights from raw data. Covering Python, Pandas, statistical analysis, and data visualization techniques used by top tech companies."
  },
  {
    id: "web-development",
    title: "Web Development",
    instructor: "Bhavani Shankar",
    lectures: 25,
    weeks: 10,
    price: 5000,
    image: "/card-web.jpg",
    level: "Beginner",
    students: "12,800",
    description: "Build modern, responsive websites from scratch using HTML, CSS, JavaScript, and Bootstrap. A perfect starting point for aspiring frontend developers."
  },
  {
    id: "cloud-computing",
    title: "Cloud Computing",
    instructor: "Suresh",
    lectures: 24,
    weeks: 9,
    price: 5000,
    image: "/cloud.jpg",
    level: "Intermediate",
    students: "6,300",
    description: "Understand cloud architecture and deployment models. Get hands-on experience with core cloud services, scalability, and infrastructure management."
  },
  {
    id: "ethical-hacking",
    title: "Ethical Hacking",
    instructor: "Suresh",
    lectures: 25,
    weeks: 9,
    price: 5000,
    image: "/hacking.jpg",
    level: "Intermediate",
    students: "9,150",
    description: "Learn to identify vulnerabilities and secure networks. Explore penetration testing methodologies, cryptography, and defense strategies against cyber threats."
  },
  {
    id: "java-programming",
    title: "Java",
    instructor: "Bhavani Shankar",
    lectures: 25,
    weeks: 7,
    price: 5000,
    image: "/full-stack.jpg",
    level: "Beginner",
    students: "15,200",
    description: "Master Object-Oriented Programming with Java. Learn core concepts, data structures, and how to build robust backend applications."
  },
  {
    id: "react-js",
    title: "React",
    instructor: "Bhavani Shankar",
    lectures: 25,
    weeks: 10,
    price: 5000,
    image: "/card-web.jpg",
    level: "Intermediate",
    students: "11,500",
    description: "Build interactive UI components with React.js. Learn state management, hooks, routing, and modern frontend development workflows."
  },
  {
    id: "full-stack-development",
    title: "Full Stack (React, Django, MySQL)",
    instructor: "Kranthi",
    lectures: 25,
    weeks: 8,
    price: 5000,
    image: "/full-stack.jpg",
    level: "Advanced",
    students: "7,800",
    description: "Become a complete developer. Build scalable backends with Django, dynamic frontends with React, and manage databases using MySQL."
  },
  {
    id: "internet-of-things",
    title: "Internet of Things",
    instructor: "Suresh",
    lectures: 28,
    weeks: 10,
    price: 5000,
    image: "/iot.jpg",
    level: "Intermediate",
    students: "4,200",
    description: "Connect the physical world to the digital. Learn embedded systems programming, sensor integration, and IoT cloud platforms."
  },
  {
    id: "embedded-systems",
    title: "Embedded Systems",
    instructor: "Suresh",
    lectures: 26,
    weeks: 10,
    price: 5000,
    image: "/iot.jpg",
    level: "Advanced",
    students: "3,800",
    description: "Dive into microcontroller programming. Learn C/C++ for embedded devices, RTOS concepts, and hardware-software interfacing."
  },
  {
    id: "hybrid-electric-vehicles",
    title: "Hybrid and Electric Vehicles",
    instructor: "Kranthi",
    lectures: 25,
    weeks: 10,
    price: 5000,
    image: "/ev.jpg",
    level: "Intermediate",
    students: "5,500",
    description: "Explore the future of automotive engineering. Understand battery management systems, power electronics, and EV drivetrain architecture."
  },
  {
    id: "robotics",
    title: "Robotics",
    instructor: "Kranthi",
    lectures: 25,
    weeks: 10,
    price: 5000,
    image: "/iot.jpg",
    level: "Intermediate",
    students: "4,900",
    description: "Build and program autonomous robots. Learn kinematics, sensor fusion, and control algorithms used in modern robotics."
  },
  {
    id: "autocad",
    title: "AutoCAD",
    instructor: "Bhavani Shankar",
    lectures: 25,
    weeks: 8,
    price: 5000,
    image: "/autocad.jpg",
    level: "Beginner to Intermediate",
    students: "6,100",
    description: "Master computer-aided design. Learn 2D drafting, 3D modeling, and create professional engineering drawings and architectural layouts."
  },
  {
    id: "construction-planning",
    title: "Construction Planning Management",
    instructor: "Bhavani Shankar",
    lectures: 25,
    weeks: 9,
    price: 5000,
    image: "/construction.jpg",
    level: "Intermediate",
    students: "3,200",
    description: "Learn essential project management skills for the construction industry, including scheduling, cost estimation, and resource allocation."
  },
  {
    id: "finance",
    title: "Finance",
    instructor: "Sumith D",
    lectures: 24,
    weeks: 9,
    price: 5000,
    image: "/finance.jpg",
    level: "Beginner",
    students: "8,900",
    description: "Understand corporate finance, financial modeling, and investment analysis to make data-driven business decisions."
  },
  {
    id: "human-resources",
    title: "Human Resources ( HR )",
    instructor: "Sumith D",
    lectures: 26,
    weeks: 13,
    price: 5000,
    image: "/hr.jpg",
    level: "Beginner to Intermediate",
    students: "7,400",
    description: "Master modern HR practices, including talent acquisition, employee relations, organizational behavior, and performance management."
  },
  {
    id: "digital-marketing",
    title: "Digital Marketing",
    instructor: "Sumith D",
    lectures: 25,
    weeks: 10,
    price: 5000,
    image: "/card-marketing.jpg",
    level: "Beginner",
    students: "13,100",
    description: "Learn SEO, social media marketing, content strategy, and PPC advertising to drive growth and build brand awareness online."
  },
  {
    id: "stock-marketing",
    title: "Stock Marketing",
    instructor: "Sumith D",
    lectures: 25,
    weeks: 12,
    price: 5000,
    image: "/finance.jpg",
    level: "Intermediate",
    students: "7,901",
    description: "Our Stock Market with Python internship offers an exciting opportunity to gain hands-on experience in the world of stock trading and financial markets, while learning how to use Python for data analysis and algorithmic trading."
  }
];

export function getCourseBySlug(slug: string) {
  return courses.find((course) => course.id === slug);
}